on:
  schedule:
    - cron:  "0 0 * * SAT"
  workflow_dispatch:

name: test-all-secrets

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      POLAR_ACCESS: ${{ secrets.SURF_POLAR_ACCESSTOKEN }}
      POLAR_USERID: ${{ secrets.SURF_POLAR_USERID }}
    steps:
      - uses: actions/checkout@v3
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - run: echo "Value of MY_SECRET $TEST_SECRET"
