on:
  schedule:
    - cron:  "0 0 * * SAT"
  workflow_dispatch:

name: test-secrets

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      POLAR_ACCESS: ${{ secrets.SURF_POLAR_ACCESSTOKEN }}
      POLAR_USERID: ${{ secrets.SURF_POLAR_USERID }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr
            any::tidyverse
            any::yaml
            any::jsonlite
      
      - uses: actions/checkout@v3
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - run: echo "Value of MY_SECRET: $TEST_SECRET"

      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Execute Script
        run: |
          Rscript "R/download_latest_surfs.R"

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"-
